---
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        restart: always
        ports:
            - '${INTERFACE}:80:80'
            - '${INTERFACE}:443:443'
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./certs:/etc/nginx/certs
            - ./vhost.d:/etc/nginx/vhost.d
            - ./html:/usr/share/nginx/html
        networks:
            bitrixdock:
        environment:
            TZ: Europe/Moscow

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nginx-proxy-le
        restart: always
        depends_on:
            - nginx-proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./certs:/etc/nginx/certs:rw
            - ./vhost.d:/etc/nginx/vhost.d
            - ./html:/usr/share/nginx/html
        environment:
            NGINX_PROXY_CONTAINER: nginx-proxy
            TZ: Europe/Moscow
        networks:
            bitrixdock:

    php:
        build: ./php/${PHP_VERSION}
        volumes:
            - ${SITE_PATH}:/var/www/bitrix
            - ./logs/php:/var/log/php
            - /etc/localtime:/etc/localtime/:ro
        environment:
            TZ: Europe/Moscow
        networks:
            - bitrixdock
        restart: unless-stopped
        extra_hosts:
            - "bitrix.local:172.18.0.9"

    web_server:
        build: ./${WEB_SERVER_TYPE}
        volumes:
            - ${SITE_PATH}:/var/www/bitrix
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - /etc/localtime:/etc/localtime/:ro
        expose:
            - "80"
        environment:
            TZ: Europe/Moscow
            VIRTUAL_HOST: seliger-city.ru,www.seliger-city.ru
            LETSENCRYPT_HOST: seliger-city.ru,www.seliger-city.ru
            LETSENCRYPT_EMAIL: your@email.ru
        networks:
            bitrixdock:
                ipv4_address: 172.18.0.9
        restart: unless-stopped
        extra_hosts:
            - "push-server-sub:172.18.0.10"
            - "push-server-pub:172.18.0.11"


    db:
        build: ./${DB_SERVER_TYPE}
        volumes:
            - ./${DB_SERVER_TYPE}/init:/docker-entrypoint-initdb.d
            - ./logs/db:/var/log/mysql
            - /etc/localtime:/etc/localtime/:ro
            - db:/var/lib/mysql
        ports:
            - '${INTERFACE}:3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            TZ: Europe/Moscow
        networks:
            - bitrixdock
        restart: unless-stopped

    memcached:
        image: memcached:latest
        networks:
            - bitrixdock
        environment:
            TZ: Europe/Moscow
        restart: unless-stopped

    adminer:
        image: dockette/adminer:full
        ports:
            - '${INTERFACE}:8080:80'
        environment:
            UPLOAD: 1024M # upload_max_filesize, post_max_size
            TZ: Europe/Moscow
        restart: unless-stopped
        networks:
            - bitrixdock
        profiles:
            - admin

    push-server-sub:
        image: ikarpovich/bitrix-push-server
        networks:
            bitrixdock:
                ipv4_address: 172.18.0.10
        environment:
            - REDIS_HOST=redis
            - LISTEN_HOSTNAME=0.0.0.0
            - LISTEN_PORT=8010
            - SECURITY_KEY=testtesttest
            - MODE=sub
        depends_on:
            - redis
        profiles:
            - push

    push-server-pub:
        image: ikarpovich/bitrix-push-server
        networks:
            bitrixdock:
                ipv4_address: 172.18.0.11
        environment:
            - REDIS_HOST=redis
            - LISTEN_HOSTNAME=0.0.0.0
            - LISTEN_PORT=8010
            - SECURITY_KEY=testtesttest
            - MODE=pub
        depends_on:
            - redis
        profiles:
            - push

    redis:
        image: redis
        networks:
            - bitrixdock
        profiles:
            - push

volumes:
    db:
        driver: local

networks:
    bitrixdock:
        ipam:
            config:
                - subnet: 172.18.0.0/24
